import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const contractMigration = 'supabase/migrations/20260908103000_customer_form_booking_contract.sql';
const hotfixMigration = 'supabase/migrations/20260909130000_customer_form_booking_rpc_ambiguity_hotfix.sql';

async function expectDatabaseError(run, code) {
  await assert.rejects(run, (error) => error.code === code);
}

test('Customer Form public RPCs execute atomically against PostgreSQL', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create schema private;
      create schema auth;
      create role anon;
      create role authenticated;

      create function auth.uid() returns uuid language sql stable as
        $$ select null::uuid $$;
      create function private.has_business_role(bigint, text[] default null)
        returns boolean language sql stable as $$ select false $$;

      create table public.businesses (
        id bigint primary key,
        business_slug text not null unique,
        booking_model_version integer not null default 2
      );
      create table public.services (
        id bigint primary key,
        business_id bigint not null,
        slug text not null,
        is_active boolean not null default true,
        is_published boolean not null default true,
        is_internal boolean not null default false,
        enrollment_mode text,
        enrollment_closed boolean not null default false,
        capacity integer not null default 1,
        cohort_start_date date
      );
      create table public.booking_custom_fields (
        id bigint generated by default as identity primary key,
        business_id bigint not null,
        field_label text not null,
        field_type text not null,
        is_required boolean not null default false,
        display_order integer not null default 0,
        is_active boolean not null default true,
        field_options text,
        system_key text,
        is_locked boolean not null default false
      );
      create table public.bookings (
        id uuid primary key default gen_random_uuid(),
        business_id bigint not null,
        service_id bigint,
        scheduled_session_id bigint,
        customer_name text,
        customer_email text,
        customer_phone text,
        quantity integer not null default 1,
        custom_data jsonb not null default '{}'::jsonb,
        reference text not null,
        starts_at timestamptz not null,
        ends_at timestamptz not null
      );
      create table public.class_enrollments (
        id bigint generated always as identity primary key,
        business_id bigint not null,
        service_id bigint not null,
        reference text not null,
        customer_name text,
        guardian_name text,
        customer_email text,
        customer_phone text,
        quantity integer,
        joins_on date,
        status text,
        notes text,
        student_date_of_birth date,
        school_grade text,
        enquiry_status text,
        consent_to_contact boolean,
        custom_data jsonb
      );
      create table public.reservations (id bigint generated always as identity primary key);

      create function public.create_public_booking(
        p_business_slug text, p_service_slug text, p_staff_slug text,
        p_starts_at timestamptz, p_customer_name text,
        p_customer_email text, p_customer_phone text, p_notes text
      ) returns table (booking_id uuid, reference text, starts_at timestamptz, ends_at timestamptz)
      language plpgsql security definer set search_path = '' as $$
      declare v_business_id bigint; v_service_id bigint; v_id uuid; v_reference text;
      begin
        select business.id, service.id into v_business_id, v_service_id
        from public.businesses business
        join public.services service on service.business_id = business.id
        where lower(business.business_slug) = lower(p_business_slug)
          and lower(service.slug) = lower(p_service_slug)
          and service.is_active and service.is_published;
        if v_service_id is null then raise exception 'Service or staff member not found' using errcode = 'P0002'; end if;
        v_id := gen_random_uuid(); v_reference := 'BK-' || left(v_id::text, 8);
        insert into public.bookings(id,business_id,service_id,customer_name,customer_email,customer_phone,reference,starts_at,ends_at)
        values(v_id,v_business_id,v_service_id,p_customer_name,p_customer_email,p_customer_phone,v_reference,p_starts_at,p_starts_at + interval '1 hour');
        return query select v_id,v_reference,p_starts_at,p_starts_at + interval '1 hour';
      end $$;

      create function public.create_public_session_booking(
        p_business_slug text, p_service_slug text, p_session_id bigint,
        p_customer_name text, p_customer_email text, p_customer_phone text,
        p_notes text, p_quantity integer
      ) returns table (booking_id uuid, reference text, starts_at timestamptz, ends_at timestamptz)
      language plpgsql security definer set search_path = '' as $$
      declare v_business_id bigint; v_service_id bigint; v_id uuid; v_reference text; v_start timestamptz;
      begin
        select business.id, service.id into v_business_id, v_service_id
        from public.businesses business
        join public.services service on service.business_id = business.id
        where lower(business.business_slug) = lower(p_business_slug)
          and lower(service.slug) = lower(p_service_slug)
          and service.is_active and service.is_published;
        if v_service_id is null then raise exception 'Service or session not found' using errcode = 'P0002'; end if;
        v_id := gen_random_uuid(); v_reference := 'BK-' || left(v_id::text, 8);
        v_start := timestamptz '2030-01-02 09:00:00+00' + make_interval(hours => p_session_id::integer);
        insert into public.bookings(id,business_id,service_id,scheduled_session_id,customer_name,customer_email,customer_phone,quantity,reference,starts_at,ends_at)
        values(v_id,v_business_id,v_service_id,p_session_id,p_customer_name,p_customer_email,p_customer_phone,p_quantity,v_reference,v_start,v_start + interval '1 hour');
        return query select v_id,v_reference,v_start,v_start + interval '1 hour';
      end $$;

      create function public.create_canonical_restaurant_booking(
        p_business_id bigint, p_customer_name text, p_phone text,
        p_reservation_date date, p_reservation_time time, p_party_size integer,
        p_special_request text, p_custom_data jsonb, p_customer_email text
      ) returns public.bookings language plpgsql security definer set search_path = '' as $$
      declare v_booking public.bookings%rowtype; v_service_id bigint;
      begin
        select service.id into v_service_id from public.services service
        where service.business_id = p_business_id and service.slug = 'restaurant';
        insert into public.bookings(business_id,service_id,customer_name,customer_email,customer_phone,quantity,custom_data,reference,starts_at,ends_at)
        values(p_business_id,v_service_id,p_customer_name,p_customer_email,p_phone,p_party_size,p_custom_data,'RS-TEST',
          p_reservation_date + p_reservation_time, p_reservation_date + p_reservation_time + interval '2 hours')
        returning * into v_booking;
        return v_booking;
      end $$;
    `);

    await db.exec(await readFile(contractMigration, 'utf8'));

    await db.exec(`
      insert into public.businesses(id,business_slug) values
        (1,'general'),(2,'restaurant-demo'),(3,'learning'),(4,'other-tenant');
      insert into public.services(id,business_id,slug,enrollment_mode,capacity,cohort_start_date,is_internal) values
        (11,1,'appointment',null,1,null,false),
        (12,1,'scheduled-class',null,10,null,false),
        (21,2,'restaurant',null,20,null,true),
        (31,3,'learning-session',null,10,null,false),
        (32,3,'learning-enquiry','cohort',5,date '2030-01-01',false);
      insert into public.booking_custom_fields
        (id,business_id,field_label,field_type,is_required,display_order,field_options) values
        (101,1,'Reason','text',true,1,null),
        (102,1,'Visit type','dropdown',true,2,E'First visit\\nFollow-up'),
        (201,2,'Accessibility','checkbox',true,1,null),
        (301,3,'Student name','text',true,1,null),
        (302,3,'Learning goal','textarea',true,2,null),
        (401,4,'Private other-tenant field','text',true,1,null);
    `);

    const validGeneralArgs = `'general','appointment','staff-a','2030-01-02 08:00:00+00',
      'Test Customer','test@example.invalid','0000000000',null,
      '{"101":"Consultation","102":"First visit"}'`;
    await expectDatabaseError(
      () => db.query(`select * from public.create_public_booking(${validGeneralArgs})`),
      '42702',
    );
    await expectDatabaseError(() => db.query(`select * from public.create_public_session_booking(
      'general','scheduled-class',1,'Test Customer','test@example.invalid','0000000000',null,2,
      '{"101":"Group booking","102":"Follow-up"}'
    )`), '42702');
    assert.equal((await db.query('select count(*)::integer count from public.bookings')).rows[0].count, 0);

    await db.exec(await readFile(hotfixMigration, 'utf8'));

    const standard = await db.query(`select * from public.create_public_booking(
      'general','appointment','staff-a','2030-01-02 08:00:00+00',
      'Test Customer','test@example.invalid','0000000000',null,
      '{"101":"Consultation","102":"First visit","401":"leak","999":"unknown","_field_labels":{"101":"Forged"}}'
    )`);
    assert.equal(standard.rows.length, 1);
    assert.match(standard.rows[0].reference, /^BK-[0-9a-f]{8}$/i);
    const standardData = await db.query('select business_id,service_id,custom_data from public.bookings where id=$1', [standard.rows[0].booking_id]);
    assert.equal(standardData.rows[0].business_id, 1);
    assert.equal(standardData.rows[0].service_id, 11);
    assert.deepEqual(standardData.rows[0].custom_data, {
      101: 'Consultation', 102: 'First visit',
      _field_labels: { 101: 'Reason', 102: 'Visit type' },
    });

    const scheduled = await db.query(`select * from public.create_public_session_booking(
      'general','scheduled-class',1,'Test Customer','test@example.invalid','0000000000',null,2,
      '{"101":"Group booking","102":"Follow-up"}'
    )`);
    assert.equal(scheduled.rows.length, 1);
    const scheduledData = await db.query('select business_id,service_id,scheduled_session_id,custom_data from public.bookings where id=$1', [scheduled.rows[0].booking_id]);
    assert.equal(scheduledData.rows[0].business_id, 1);
    assert.equal(scheduledData.rows[0].service_id, 12);
    assert.equal(scheduledData.rows[0].scheduled_session_id, 1);
    assert.deepEqual(scheduledData.rows[0].custom_data, {
      101: 'Group booking', 102: 'Follow-up',
      _field_labels: { 101: 'Reason', 102: 'Visit type' },
    });

    const restaurant = await db.query(`select public.create_public_restaurant_reservation(
      'restaurant-demo','Test Diner','0000000000','2030-01-03','18:00',2,null,
      '{"201":true,"customer_email":"diner@example.invalid","_field_labels":{"201":"Forged"}}'
    ) reference`);
    assert.equal(restaurant.rows[0].reference, 'RS-TEST');
    const restaurantData = await db.query("select customer_email,custom_data from public.bookings where reference='RS-TEST'");
    assert.equal(restaurantData.rows[0].customer_email, 'diner@example.invalid');
    assert.deepEqual(restaurantData.rows[0].custom_data, { 201: true, _field_labels: { 201: 'Accessibility' } });
    const restaurantRelationship = await db.query(`select service.is_internal
      from public.bookings booking join public.services service on service.id=booking.service_id
      where booking.reference='RS-TEST'`);
    assert.equal(restaurantRelationship.rows[0].is_internal, true);
    assert.equal((await db.query('select count(*)::integer count from public.reservations')).rows[0].count, 0);

    const learningSession = await db.query(`select * from public.create_public_session_booking(
      'learning','learning-session',2,'Test Student','guardian@example.invalid','0000000000',null,1,
      '{"301":"Test Student","302":"Exam preparation"}'
    )`);
    assert.equal(learningSession.rows.length, 1);
    const learningSessionData = await db.query('select business_id,service_id,scheduled_session_id,custom_data from public.bookings where id=$1', [learningSession.rows[0].booking_id]);
    assert.equal(learningSessionData.rows[0].business_id, 3);
    assert.equal(learningSessionData.rows[0].service_id, 31);
    assert.equal(learningSessionData.rows[0].scheduled_session_id, 2);
    assert.deepEqual(learningSessionData.rows[0].custom_data, {
      301: 'Test Student', 302: 'Exam preparation',
      _field_labels: { 301: 'Student name', 302: 'Learning goal' },
    });

    const enquiry = await db.query(`select * from public.create_public_class_enquiry(
      'learning','learning-enquiry','Test Guardian','Test Student','guardian@example.invalid','0000000000',
      '2020-01-01','Grade 1','2030-01-02',null,true,'{"302":"Build confidence","401":"leak"}'
    )`);
    assert.equal(enquiry.rows[0].remaining, 4);
    const enquiryData = await db.query('select custom_data from public.class_enrollments');
    assert.deepEqual(enquiryData.rows[0].custom_data, { 302: 'Build confidence', _field_labels: { 302: 'Learning goal' } });

    const beforeFailures = (await db.query('select count(*)::integer count from public.bookings')).rows[0].count;
    await expectDatabaseError(() => db.query(`select * from public.create_public_booking(
      'general','appointment','staff-a','2030-01-04 08:00:00+00','Test','x@example.invalid','000',null,
      '{"102":"First visit"}')`), '22023');
    await expectDatabaseError(() => db.query(`select * from public.create_public_booking(
      'general','appointment','staff-a','2030-01-04 09:00:00+00','Test','x@example.invalid','000',null,
      '{"101":"Reason","102":"Not configured"}')`), '22023');
    const afterFailures = (await db.query('select count(*)::integer count from public.bookings')).rows[0].count;
    assert.equal(afterFailures, beforeFailures, 'failed normalization must roll back the underlying booking insert');

    const overloads = await db.query(`select proname,pronargs from pg_proc
      where pronamespace='public'::regnamespace
        and proname in ('create_public_booking','create_public_session_booking')
      order by proname,pronargs`);
    assert.deepEqual(overloads.rows.map(({ proname, pronargs }) => [proname, Number(pronargs)]), [
      ['create_public_booking', 8], ['create_public_booking', 9],
      ['create_public_session_booking', 8], ['create_public_session_booking', 9],
    ]);

    const privileges = await db.query(`select p.proname,
      has_function_privilege('public',p.oid,'execute') public_execute,
      has_function_privilege('anon',p.oid,'execute') anon_execute,
      has_function_privilege('authenticated',p.oid,'execute') authenticated_execute,
      p.prosecdef, p.proconfig
      from pg_proc p where p.pronamespace='public'::regnamespace
        and ((p.proname='create_public_booking' and p.pronargs=9)
          or (p.proname='create_public_session_booking' and p.pronargs=9))`);
    for (const privilege of privileges.rows) {
      assert.equal(privilege.public_execute, false);
      assert.equal(privilege.anon_execute, true);
      assert.equal(privilege.authenticated_execute, true);
      assert.equal(privilege.prosecdef, true);
      assert.deepEqual(privilege.proconfig, ['search_path=""']);
    }
    const privatePrivileges = await db.query(`select
      has_function_privilege('public','private.normalize_public_customer_form_data(bigint,jsonb,text[])','execute') public_execute,
      has_function_privilege('anon','private.normalize_public_customer_form_data(bigint,jsonb,text[])','execute') anon_execute,
      has_function_privilege('authenticated','private.normalize_public_customer_form_data(bigint,jsonb,text[])','execute') authenticated_execute`);
    assert.deepEqual(privatePrivileges.rows[0], {
      public_execute: false, anon_execute: false, authenticated_execute: false,
    });
  } finally {
    await db.close();
  }
});
